### ISSUE TITLE
when i use VF, it says only support 16 queues，how can i use more ?

### ISSUE THREAD

**Issue by lucky-wavespider** [intel/ethernet-linux-ice#11]
When i tested vfs in dpdk, use more than 16 queues one vf, it always failed.
DPDK version is 22.11.2, ice version is 1.14.13 and nic is e810. And Each NIC have 4 vfs.
Then i checked the ice driver code. In function ice_vsi_set_dflt_rss_params,  i saw some code below:
	case ICE_VSI_VF:
		if (vsi->rss_lut_type != ICE_LUT_VSI)
			break;
		if (vsi->alloc_rxq > ICE_MAX_RSS_QS_PER_VF) {
			dev_info(dev, "Promoting VSI %d to GLOBAL LUT.\n",
				 vsi->idx);
			vsi->rss_lut_type = ICE_LUT_GLOBAL;
			vsi->rss_table_size = ICE_LUT_GLOBAL_SIZE;
			vsi->rss_size = ICE_MAX_MEDIUM_RSS_QS;
			break;
		}
		/* VF VSI will get a small RSS table.
		 * For VSI_LUT, LUT size should be set to 64 bytes.
		 */
		vsi->rss_table_size = ICE_LUT_VSI_SIZE;
		vsi->rss_size = ICE_MAX_RSS_QS_PER_VF;
		vsi->rss_lut_type = ICE_LUT_VSI;
		break;

vsi->alloc_rxq always < ICE_MAX_RSS_QS_PER_VF, and always set rss_lut_type to ICE_LUT_VSI;
How can i changed to ICE_LUT_GLOBAL to allow more queues?
And i don't understand what's different between ICE_LUT_GLOBAL and ICE_LUT_VSI;

when it changed to ICE_LUT_GLOBAL, in function ice_vc_get_vf_res_msg, will have the flag VIRTCHNL_VF_LARGE_NUM_QPAIRS : 

	if (vf->driver_caps & VIRTCHNL_VF_LARGE_NUM_QPAIRS &&
	    vsi->rss_lut_type != ICE_LUT_VSI)
		vfres->vf_cap_flags |= VIRTCHNL_VF_LARGE_NUM_QPAIRS;

Then can have more than 16 queues in one vf.

**Comment by pkitszel** [comment]
please refer to the readme file:
https://github.com/intel/ethernet-linux-ice/blob/main/README#L3759

for future requests I recommend to contact our customer support
