### ISSUE TITLE
Recurring card resets after ICE OICR event notification: oicr = 0x06000803 / HMC Error on 3 seperate machines

### ISSUE THREAD

**Issue by secabeen** [intel/ethernet-linux-ice#12]
I have three SYS-111C-NR servers with AOC-A25G-i2SM NICs that leverage the Intel E810-XXVAM2 controller under Proxmox PVE using the `ice` driver that are regularly resetting the NIC with a OICR / HMC error when loaded.  

**Issue Description**
These issues are intermittent, but regular, and occur on all three systems. 

**Driver Version**
ice-1.14.11, but also occurred on older versions, including the driver included with Linux Kernel 6.8.12.

**Custom Code**
No

**Reproduction Steps**
```
1. Run somewhat network intensive VMs on latest Proxmox PVE.
2. Wait some hours to days.
3. Observe NIC reset.
```

**Expected Behavior**
Card does not reset.

**Actual Behavior**
Card is reset by driver and interrupts established connections.

**Additional Information**
Other users report similar issues on other OEM hardware based around the E810-XXVAM2, and also report that the issue does not appear on other Hypervisors such as ESXi.  One report shows improvement after BIOS update and card replacement.  We have three servers, which reduces likelihood of individual card failure.  BIOS updates through May 2024 were installed in an attempt to resolve the problem, without success.

Details of other report: https://forum.proxmox.com/threads/network-crash-after-3-or-4-hours.122328/

**Relevant Log Output**
```
[Thu Oct 17 09:38:49 2024] ice 0000:c7:00.0 irdma1: ICE OICR event notification: oicr = 0x06000803
[Thu Oct 17 09:38:49 2024] ice 0000:c7:00.0 irdma1: HMC Error
[Thu Oct 17 09:38:49 2024] ice 0000:c7:00.0 irdma1: Requesting a reset
[Thu Oct 17 09:38:49 2024] infiniband irdma1: ib_query_port failed (-19)
[Thu Oct 17 09:38:49 2024] irdma_dbg_pf_exit: removing debugfs entries
[Thu Oct 17 09:38:49 2024] dmar_fault: 311 callbacks suppressed
[Thu Oct 17 09:38:49 2024] DMAR: DRHD: handling fault status reg 2
[Thu Oct 17 09:38:49 2024] DMAR: [DMA Read NO_PASID] Request device [c7:00.0] fault addr 0x844b7000 [fault reason 0x71] SM: Present bit in first-level paging entry is clear
[Thu Oct 17 09:38:49 2024] DMAR: DRHD: handling fault status reg 2
[Thu Oct 17 09:38:49 2024] DMAR: [DMA Read NO_PASID] Request device [c7:00.0] fault addr 0x844b7000 [fault reason 0x71] SM: Present bit in first-level paging entry is clear
[Thu Oct 17 09:38:49 2024] DMAR: DRHD: handling fault status reg 2
[Thu Oct 17 09:38:49 2024] DMAR: [DMA Read NO_PASID] Request device [c7:00.0] fault addr 0x844b7000 [fault reason 0x71] SM: Present bit in first-level paging entry is clear
[Thu Oct 17 09:38:49 2024] DMAR: DRHD: handling fault status reg 2
[Thu Oct 17 09:38:49 2024] vmbr0: port 1(enp199s0f0np0) entered disabled state
[Thu Oct 17 09:38:49 2024] ice 0000:c7:00.1: Failed to  disable iWARP filtering
[Thu Oct 17 09:38:49 2024] enp199s0f1np1 speed is unknown, defaulting to 1000
[Thu Oct 17 09:38:49 2024] infiniband irdma0: ib_query_port failed (-19)
[Thu Oct 17 09:38:49 2024] irdma_dbg_pf_exit: removing debugfs entries
[Thu Oct 17 09:38:49 2024] ice 0000:c7:00.1 irdma0: WS: LAN free_res for rdma qset failed.
[Thu Oct 17 09:38:51 2024] ice 0000:c7:00.1: The DDP package was successfully loaded: ICE OS Default Package version 1.3.36.0
[Thu Oct 17 09:38:51 2024] ice 0000:c7:00.1: PTP reset successful
[Thu Oct 17 09:38:51 2024] ice 0000:c7:00.0: DDP package already present on device: ICE OS Default Package version 1.3.36.0
[Thu Oct 17 09:38:51 2024] ice 0000:c7:00.0: PTP reset successful
[Thu Oct 17 09:38:52 2024] ice 0000:c7:00.1: VSI rebuilt. VSI index 0, type ICE_VSI_PF
[Thu Oct 17 09:38:52 2024] ice 0000:c7:00.1: VSI rebuilt. VSI index 1, type ICE_VSI_CTRL
[Thu Oct 17 09:38:52 2024] probe: cdev_info=00000000ab54a062, cdev_info->dev.aux_dev.bus->number=199, cdev_info->rdma_active_port=0xff netdev=enp199s0f1np1
[Thu Oct 17 09:38:52 2024] ice 0000:c7:00.1: irdma_fill_device_info: iwdev->lag_mode = 0
[Thu Oct 17 09:38:55 2024] ice 0000:c7:00.0: VSI rebuilt. VSI index 0, type ICE_VSI_PF
[Thu Oct 17 09:38:55 2024] vmbr0: port 1(enp199s0f0np0) entered blocking state
[Thu Oct 17 09:38:55 2024] vmbr0: port 1(enp199s0f0np0) entered forwarding state
[Thu Oct 17 09:38:55 2024] ice 0000:c7:00.0: VSI rebuilt. VSI index 1, type ICE_VSI_CTRL
[Thu Oct 17 09:38:55 2024] probe: cdev_info=000000004ce78438, cdev_info->dev.aux_dev.bus->number=199, cdev_info->rdma_active_port=0xff netdev=enp199s0f0np0
[Thu Oct 17 09:38:55 2024] ice 0000:c7:00.0: irdma_fill_device_info: iwdev->lag_mode = 0
[Thu Oct 17 09:38:55 2024] ice 0000:c7:00.0 enp199s0f0np0: NIC Link is Down
[Thu Oct 17 09:38:56 2024] ice 0000:c7:00.0 enp199s0f0np0: NIC Link is up 10 Gbps Full Duplex, Requested FEC: NONE, Negotiated FEC: NONE, Autoneg Advertised: On, Autoneg Negotiated: False, Flow Control: None
```

**Comment by firth** [comment]
Same here

**Comment by noppel** [comment]
I had the same problems. I have a supermicro server and various other pcs (shuttle). The problem is the same everywhere. It is not supermicro related. However I have problems with three or every SAS controllers brand I have tried. They are being reset every few days. Sometimes after a month, sometimes after 24 hours. I have had contact with supermicro and I have basically updated the SuperMicro BIOS, the SAS Adapter BIOS and the Intel i810 Bios (was quite complicated). 
What I am basically doing for now is I have a script listening on the journal and doing a reboot if "HMC Error" occurs. For the SAS issue, I have no sultion yet (maybe the supermicro enclosure is faulty).
I am also using the kernel driver from intel (instead or additional to the kernel one). Fortunately the "HMC Error" did no longer occur with me so there is a high probabilty that the same will happen in your scenario, if you are either using the latest 6.8 kernel (standard proxmox), Intel driver or having done the SM or Intel BIOS updates.

**Comment by lczapnik** [comment]
From the log attached I can see an irdma driver is requesting a reset. Do you run RDMA traffic? If not you may try to unload (and blacklist) irdma driver.

I asked internal validation teams if they observed similar issues.

Thank you for raising the issue!

**Comment by secabeen** [comment]
I have unloaded the irdma (and associated ib_*) drivers on the server that was most prone to the issue, and the problem has not recurred.  I've expanded my test, and unloaded the irdma module on more of our servers and will let that run through Monday.  If we haven't seen the issue recur by Monday, I think we can declare it related to RDMA and implement that workaround globally.  I'll post back then.

**Comment by secabeen** [comment]
Removing or preventing the loading of the DMA/IB models does eliminate this error.  I would recommend that further diagnosis be done into the DMA issues, but as someone who doesn't use the DMA/IB features, I have a functional workaround.  I'll close the issue for now and let you open a new one on the DMA issues if needed.

**Comment by kikoreis** [comment]
@secabeen can you confirm (or remember) what version of nic firmware (via lshw) and kernel you were running on the host that crashed? I'm seeing a similar crash in irdma (though the OICR is 0x04000003) on 5.15.0 running firmware 4.20/22.09.

**Comment by secabeen** [comment]
Here you go, one each from the SFP and Copper NICs:

`        *-network:0
             description: Ethernet interface
             product: Ethernet Controller E810-XXV for SFP
             vendor: Intel Corporation
             physical id: 0
             bus info: pci@0000:c7:00.0
             logical name: enp199s0f0np0
             version: 02
             serial: 3c:ec:ef:e0:ef:50
             size: 10Gbit/s
             capacity: 25Gbit/s
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi msix pciexpress vpd bus_master cap_list rom ethernet physical fibre 1000bt-fd 25000bt-fd
             configuration: autonegotiation=off broadcast=yes driver=ice driverversion=6.8.12-9-pve duplex=full firmware=4.30 0x8001c056 1.3429.0 latency=0 link=yes multicast=yes speed=10Gbit/s
             resources: iomemory:217f0-217ef iomemory:217f0-217ef irq:16 memory:217ffa000000-217ffbffffff memory:217ffe010000-217ffe01ffff memory:fae00000-faefffff memory:217ffd000000-217ffdffffff memory:217ffe220000-217ffe41ffff`

`        *-network:0
             description: Ethernet interface
             product: Ethernet Controller X710 for 10GBASE-T
             vendor: Intel Corporation
             physical id: 0
             bus info: pci@0000:71:00.0
             logical name: enp113s0f0np0
             version: 02
             serial: 7c:c2:55:a8:31:4c
             size: 1Gbit/s
             capacity: 10Gbit/s
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi msix pciexpress vpd bus_master cap_list rom ethernet physical tp 100bt-fd 1000bt-fd 10000bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=i40e driverversion=6.8.12-9-pve duplex=full firmware=9.00 0x8000d28f 1.3295.0 ip=10.111.91.228 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
             resources: iomemory:20ff0-20fef iomemory:20ff0-20fef irq:16 memory:20fffe000000-20fffeffffff memory:20ffff808000-20ffff80ffff memory:d2480000-d24fffff memory:20ffff400000-20ffff7fffff memory:20ffff910000-20ffffa0ffff`

**Comment by guerby** [comment]
Note: we bond all the 4 ports with the following configuration on all our servers:

```
auto bond0
iface bond0 inet manual
	bond-slaves nic0 nic1 nic2 nic3
	bond-miimon 100
	bond-mode 802.3ad
	bond-xmit-hash-policy layer3+4
	bond-lacp-rate 1
```

**Comment by liske** [comment]
> As recommended here:
> 
> https://forum.proxmox.com/threads/network-crash-after-3-or-4-hours.122328/
> 
> I will remove and blacklist irdma and ib_uverbs, ib_core as we don't use rdma nor infiniband.

It seems to be the best workaround for most setups. With the upcomming Alpine Linux 3.23 release the `irdma` module will be blacklisted by default https://github.com/alpinelinux/aports/commit/313096cd1f8f6ec031437eddcad49595c7a7eb7f 🤷
