### ISSUE TITLE
Missing ice 1.14.13 release

### ISSUE THREAD

**Issue by penguin359** [intel/ethernet-linux-ice#13]
The ice-1.14.13 release does not appear to be published here. The Git tag is also missing. This release is published on Intel's main website here:

https://www.intel.com/content/www/us/en/download/19630/830420/intel-network-adapter-driver-for-e810-series-devices-under-linux.html

This specific release is aligned with what was used in validation of our latest NVM release for certain Intel network adapters and should be available.

**Comment by lczapnik** [comment]
Hello! Thank you for pointing this out. Now, it should be available to download:
https://github.com/intel/ethernet-linux-ice/releases/tag/v1.14.13
